# Generated by Django 2.2.6 on 2019-12-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
