# Generated by Django 2.2.6 on 2019-12-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20191223_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
