# Generated by Django 2.2.6 on 2019-12-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='StoryPost',
        ),
    ]
