# Generated by Django 2.2.6 on 2019-12-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20191224_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storypost',
            name='tag',
        ),
        migrations.AddField(
            model_name='storypost',
            name='camp_id',
            field=models.IntegerField(default=0),
        ),
    ]
