# Generated by Django 2.2.6 on 2019-12-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20191224_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='camp_id',
            field=models.IntegerField(default=1),
        ),
    ]
