# Generated by Django 2.2.6 on 2019-11-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camp',
        ),
    ]
