# Generated by Django 2.2.6 on 2019-10-10 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('positions', models.IntegerField()),
                ('positions_male', models.IntegerField()),
                ('positions_female', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('extra_host_country_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('extra_host_country_fee_currency', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
