# Generated by Django 2.2.6 on 2019-10-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='published_data',
            new_name='published_date',
        ),
    ]
