# Generated by Django 2.2.6 on 2019-10-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_auto_20191013_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
