# Generated by Django 2.2.6 on 2019-11-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0005_camp_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='positions',
        ),
    ]
