# Generated by Django 2.2.6 on 2019-11-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0012_remove_camp_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
