# Generated by Django 2.2.6 on 2019-11-14 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0014_auto_20191114_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='extra_host_country_fee_currency',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
