# Generated by Django 2.2.6 on 2019-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0015_camp_extra_host_country_fee_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='extra_host_country_fee_currency',
            field=models.CharField(default='', max_length=200),
        ),
    ]
