# Generated by Django 2.2.6 on 2019-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0016_auto_20191114_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
