# Generated by Django 2.2.6 on 2019-11-14 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0017_camp_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='camp',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
