# Generated by Django 2.2.6 on 2019-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0018_auto_20191114_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='extra_host_country_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
