# Generated by Django 2.2.6 on 2019-11-14 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0019_camp_extra_host_country_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='camp',
            name='extra_host_country_fee',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
