# Generated by Django 2.2.6 on 2019-11-14 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0020_auto_20191114_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
