# Generated by Django 2.2.6 on 2019-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0021_camp_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='positions',
            field=models.IntegerField(default=0),
        ),
    ]
