# Generated by Django 2.2.6 on 2019-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0022_auto_20191114_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='positions_female',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_male',
            field=models.IntegerField(default=0),
        ),
    ]
