# Generated by Django 2.2.6 on 2019-11-14 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0024_camp_required_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='camp',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
