# Generated by Django 2.2.6 on 2019-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0027_auto_20191114_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='positions_other',
            field=models.IntegerField(default=0),
        ),
    ]
