# Generated by Django 2.2.6 on 2019-11-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0028_camp_positions_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='extra_host_country_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='camp',
            name='extra_host_country_fee_currency',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_female',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_male',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_other',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='required_language',
            field=models.CharField(blank=True, default='English', max_length=200),
        ),
    ]
