# Generated by Django 2.2.6 on 2019-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0029_auto_20191115_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='positions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_female',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_male',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_other',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
