# Generated by Django 2.2.6 on 2019-11-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0030_auto_20191115_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='positions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_female',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_male',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_other',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
