# Generated by Django 2.2.6 on 2019-11-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0031_auto_20191115_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_female',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_male',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='camp',
            name='positions_other',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='camp',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
