# Generated by Django 2.2.6 on 2019-11-15 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0032_auto_20191115_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='camp',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
