# Generated by Django 2.2.6 on 2019-11-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0036_auto_20191120_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='continent',
        ),
    ]
