# Generated by Django 2.2.6 on 2019-11-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0037_remove_camp_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='continent',
            field=models.CharField(choices=[('ASIA', 'Asia'), ('AFRICA', 'Africa'), ('ANTARCTICA', 'Antarctica'), ('AUSTRALIA', 'Australia'), ('N_AMERICA', 'North America'), ('S_AMERICA', 'South America'), ('EUROPE', 'Europe')], default=1, max_length=9),
        ),
    ]
