# Generated by Django 2.2.6 on 2019-11-22 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0038_camp_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('All', 'All'), ('ASIA', 'Asia'), ('AFRICA', 'Africa'), ('ANTARCTICA', 'Antarctica'), ('AUSTRALIA', 'Australia'), ('N_AMERICA', 'North America'), ('S_AMERICA', 'South America'), ('EUROPE', 'Europe')], default=1, max_length=10)),
                ('start_after', models.DateField(default=datetime.date.today)),
                ('end_before', models.DateField(default=datetime.date.today)),
                ('english_required', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='camp',
            name='continent',
            field=models.CharField(choices=[('ASIA', 'Asia'), ('AFRICA', 'Africa'), ('ANTARCTICA', 'Antarctica'), ('AUSTRALIA', 'Australia'), ('N_AMERICA', 'North America'), ('S_AMERICA', 'South America'), ('EUROPE', 'Europe')], default=1, max_length=10),
        ),
    ]
