# Generated by Django 2.2.6 on 2019-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0039_auto_20191122_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='continent',
            field=models.CharField(choices=[('All', 'All'), ('AFRICA', 'Africa'), ('ASIA', 'Asia'), ('ANTARCTICA', 'Antarctica'), ('AUSTRALIA', 'Australia'), ('N_AMERICA', 'North America'), ('S_AMERICA', 'South America'), ('EUROPE', 'Europe')], default=1, max_length=10),
        ),
    ]
