# Generated by Django 2.2.6 on 2019-11-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0040_auto_20191122_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='continent',
            field=models.CharField(choices=[('ALL', 'All'), ('ASIA', 'Asia'), ('AFRICA', 'Africa'), ('AUSTRALIA', 'Australia'), ('AMERICAS', 'Americas'), ('EUROPE', 'Europe')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='filtermodel',
            name='continent',
            field=models.CharField(choices=[('ALL', 'All'), ('ASIA', 'Asia'), ('AFRICA', 'Africa'), ('AUSTRALIA', 'Australia'), ('AMERICAS', 'Americas'), ('EUROPE', 'Europe')], default=1, max_length=10),
        ),
    ]
