# Generated by Django 2.2.6 on 2019-11-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0041_auto_20191122_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='continent',
            field=models.CharField(choices=[('ASIA', 'Asia'), ('AFRICA', 'Africa'), ('AUSTRALIA', 'Australia'), ('AMERICAS', 'Americas'), ('EUROPE', 'Europe')], default=1, max_length=10),
        ),
    ]
