# Generated by Django 2.2.6 on 2019-11-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0042_auto_20191123_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
