# Generated by Django 2.2.6 on 2019-11-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0043_camp_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp',
            old_name='tag',
            new_name='tagline',
        ),
    ]
