# Generated by Django 2.2.6 on 2019-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0044_auto_20191125_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
